name: Build and Release orfondl

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: Build binary for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/orfondl-linux-amd64 ./...
        shell: bash

      - name: Build binary for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/orfondl-windows-amd64.exe ./...
        shell: bash

      - name: Build binary for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/orfondl-macos-amd64 ./...
        shell: bash

      - name: Build binary for macOS arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o dist/orfondl-macos-arm64 ./...
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: Release of version ${{ github.ref_name }}

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/orfondl-linux-amd64
          asset_name: orfondl-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/orfondl-windows-amd64.exe
          asset_name: orfondl-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/orfondl-macos-amd64
          asset_name: orfondl-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/orfondl-macos-arm64
          asset_name: orfondl-macos-arm64
          asset_content_type: application/octet-stream